### ISSUE TITLE
security: identity-checked workdir deletion is implemented only in the Rust backend

### ISSUE THREAD

**Issue by aunysillyme** [The-40-Thieves/codecalc#38]
## Problem

The README states identity-checked temp-directory deletion as a flat guarantee:

> The deletion is **identity-checked**: the directory's device and inode are recorded at creation and re-checked before removal, because executed code runs with that directory as its cwd and can rename another one into its place.

The reasoning is right, and the Rust executor implements it. The Python side does not.

Rust, with the check:
- [executor/src/main.rs#L315-L341](https://github.com/The-40-Thieves/codecalc/blob/e26fa15ba403f3d7599938bdca42ad163294895a/executor/src/main.rs#L315-L341) - `dir_identity`, `remove_own_workdir`

Python, without it:
- [codecalc/executor.py#L468-L472](https://github.com/The-40-Thieves/codecalc/blob/e26fa15ba403f3d7599938bdca42ad163294895a/codecalc/executor.py#L468-L472) - `shutil.rmtree(workdir, ignore_errors=True)`
- [codecalc/server.py#L286-L288](https://github.com/The-40-Thieves/codecalc/blob/e26fa15ba403f3d7599938bdca42ad163294895a/codecalc/server.py#L286-L288) - same, in `execute_code_stream`'s `finally`
- [codecalc/sessions.py#L86-L87](https://github.com/The-40-Thieves/codecalc/blob/e26fa15ba403f3d7599938bdca42ad163294895a/codecalc/sessions.py#L86-L87) - same, in `stop`

`execute_code_stream` is the sharpest of the three: it creates a workdir, passes it as `--workdir` so executed code runs with it as cwd, and unconditionally removes it on the way out.

The comment at [codecalc/executor.py#L469-L470](https://github.com/The-40-Thieves/codecalc/blob/e26fa15ba403f3d7599938bdca42ad163294895a/codecalc/executor.py#L469-L470) reads "Same rule as the Rust executor: a caller-supplied workdir belongs to the caller." That is true of the ownership rule. The Rust path enforces two rules and the Python path implements one, so the comment reads as parity that is not there.

## Why the parity gate does not catch it

`scripts/check_parity.py` compares environment variable names and numeric constants between the two backends. A security behaviour present in one and absent in the other is outside what it inspects, which is the same shape as the gap noted in the `/proc`-walk commit where the gate never looked at `platform/unix.rs`.

## Suggested fix

Add a `_dir_identity(path)` / `_rmtree_checked(path, identity)` pair in Python mirroring `main.rs`, and use it at all three sites. Then extend `check_parity.py` to assert both backends delete through an identity-checked path, so the property is gated rather than remembered.

*Found during an external audit at `e26fa15ba403f3d7599938bdca42ad163294895a`. Static, not exploited.*

**Comment by StressTestor** [comment]
#48 closed this, and it went further than the issue asked: `_dir_identity` at
executor.py:353 and `_rmtree_checked` at :392, wired at all three Python sites,
plus the `check_parity.py` section, the `BARE_RMTREE` gate and
`_SESSION_DIR_IDENTITY` tracking. Good fix. The reason I am commenting rather
than opening something new is that the reasoning inside it applies to a corner it
did not reach, and this is where the context lives.

`_dir_identity` explains why it does not stub out on Windows:

> Attempted on EVERY platform, not just POSIX. The first version of this
> returned None on Windows outright, on the reasoning that Windows has no
> cheap stable (dev, ino) — and CI disproved it the only way that counts: the
> rename-swap regression ran on windows-latest and reported
>
>     FAIL a directory swapped in by rename is NOT deleted (python fallback)
>          -> C:\Users\...\codecalc-r7oiykyq DELETED
>
> A guard that returns None on a platform, feeding a caller that treats None
> as "delete unconditionally", is not a recorded gap. It is the guard being
> inert exactly where nobody looks, while the README states the guarantee
> flatly.

That is the version the Rust backend still has.

main.rs:329-336:

```rust
#[cfg(not(unix))]
fn dir_identity(path: &Path) -> Option<(u64, u64)> {
    // Windows has no cheap stable (dev, ino) without opening a handle. The
    // rename swap needs the sandboxed program to hold the directory open, which
    // Windows makes much harder; recorded as a gap rather than faked.
    let _ = path;
    None
}
```

main.rs:340-349:

```rust
fn remove_own_workdir(work: &Path, created: Option<(u64, u64)>) {
    if created.is_some() && dir_identity(work) != created {
        eprintln!("codecalc-exec: refusing to delete {} ...", work.display());
        return;
    }
    let _ = fs::remove_dir_all(work);
}
```

`created.is_some() &&` short-circuits when `created` is `None`, so the delete runs
unchecked, and on non-Unix that is every call. The two backends now fail in
opposite directions on the same input: Python refuses when it cannot establish
identity (executor.py:415, `if created is None: ... return False`), Rust
deletes.

I have not run the Rust path on Windows, so I am not claiming a demonstrated
deletion there. The claim is narrower and readable from the source: the guard
cannot fire, because the function it depends on returns `None` unconditionally on
that platform. The CI failure quoted above is what removes the doubt about
whether the swap is achievable on Windows at all.

Two things make it hard to notice. The parity section asserts the functions exist
and are called, and its Rust check is the regex `fn\s+dir_identity`, which the
`#[cfg(not(unix))]` stub satisfies as readily as the real one, so the gate is
green. And the rename-swap regression added in #48 forces the Python path,
`executor._rust = None` before staging the attack, so the Rust backend is not
exercised by it on any platform.

The README states the behaviour Rust does not implement, at README:366-376:

> The deletion is **identity-checked**: the directory's device and inode are
> recorded at creation and re-checked before removal ... If the filesystem
> supplies no file index to identify the directory by, the deletion is
> **refused** rather than performed unverified, so temp directories accumulate
> there instead of the wrong one being removed. That trade is stated because it is
> the one this guarantee actually makes: it was previously implemented in the Rust
> executor only, and the Python fallback deleted unconditionally, which CI caught
> on Windows.

Unqualified as to platform and backend, and the last sentence credits Rust as the
one that had it right. On Windows it is the other way round. That matters more
after #49 than it would have before: the release workflow builds the executor for
`x86_64-pc-windows-msvc` and ships it as `py3-none-win_amd64`, so a Windows
`pip install` now gets a populated `executor._rust` and takes the Rust path by
default rather than the Python fallback that refuses correctly.

One precondition that is not recorded anywhere yet, since this issue said "static,
not exploited". The primitive does work, and placing a directory at the workdir
path is an `os.rename`, which cannot cross a filesystem boundary:

```
same fs   /private/tmp -> /private/tmp: rename SUCCEEDED
same fs   $HOME        -> /private/tmp: rename SUCCEEDED
cross-dev /Volumes/T7  -> /private/tmp: OSError errno=18 (EXDEV) Cross-device link
```

So EXDEV genuinely bounds this where TMPDIR is a separate mount, and on a systemd
Linux box with `/tmp` on tmpfs the attacker is limited to directories already
inside tmpfs. It is not a bound on stock macOS:

```
/private/tmp   st_dev=16777233
TMPDIR         /var/folders/dy/.../T   st_dev=16777233
$HOME          /Users/<user>           st_dev=16777233
/Volumes/T7                            st_dev=16777244
```

TMPDIR, `/private/tmp` and `$HOME` are one device, so anything under the
operator's home directory is a valid source. Worth writing down because "needs a
same-filesystem rename" reads like a constraint until you check the default macOS
layout and find that it is not one. For completeness, a symlink swapped into the
slot is not the vector: `shutil.rmtree` refuses to recurse a symlink and with
`ignore_errors=True` that refusal is silent, so the target survives. The rename is
the vector, which is why device and inode are the right things to key on.

The essential change is to make the Rust guard fail closed, either by dropping the
`created.is_some() &&` short-circuit so `None` refuses, or by attempting
`(dev, ino)` on Windows the way the Python side now does.
`std::os::windows::fs::MetadataExt` exposes `volume_serial_number` and
`file_index`, both `Option`, which is the same information `os.lstat` gives Python
there including the case where the filesystem supplies nothing.

Credit for the original finding is aunysillyme's. I have the EXDEV measurement and
a rename-swap reproduction if either is useful for a regression test on the Rust
path. Whether this deserves reopening here or a fresh issue is your call, not
mine, which is why it is a comment.
